evm_sources:
  - node_url: "https://data-seed-prebsc-1-s1.binance.org:8545/"
    chain_name: "BSCT"
    contract_address: "0x3C957b9dc20d541a277F9546bccbe2f8EEEDd986"
saturn_node_grpc_url: "localhost:9090"
chain_id: "saturn"